Norbix30
mto-2022-pn/lab1_2 pull request #11
Opened 2022-03-11 23:14 UTC by norbix30

209382
Norbert Łodziński

2022-03-13 15:57 UTC, radamuspl requested changes

2022-03-13 15:57 UTC, radamuspl commented on src/main/java/pl/com/bottega/ecommerce/sales/domain/invoicing/BookKeeper.java
> +            TaxCalculator taxCalc = new StandardTaxCalculator();
Jaką zmienność Pan uzyska, jeżeli tworzy Pan instancję w tym miejscu? Instancja `TaxCalculatr` powinna być wstrzykiwania jako argument metody `issuance`.

2022-03-13 19:25 UTC, norbix30 commented
Rzeczywiście, nie uzyskam żadnej zmienności.
Dziękuję za uwagę, już ją zastosowałem.

2022-03-21 16:57 UTC, radamuspl approved these changes

2022-03-21 16:57 UTC, merged