Refractor
mto-2022-pn/lab1_2 pull request #2
Opened 2022-03-09 15:11 UTC by AdrianPietrz

2022-03-13 15:40 UTC, radamuspl requested changes

2022-03-13 15:40 UTC, radamuspl commented on src/main/java/pl/com/bottega/ecommerce/sales/domain/invoicing/BookKeeper.java
> +        TaxCalculator taxCalculator = TaxCalculatorFactory.createTaxCalculator();
TaxCalculator powinien być wstrzykiwany jako parameter metody issuance

2022-03-13 15:40 UTC, radamuspl commented on src/main/java/pl/com/bottega/ecommerce/sales/domain/invoicing/TaxCalculator.java
> +public class TaxCalculator {
Potrzebny jest interfejs, który ta klasa będzie implementować - kod klienta (BookKeeper) wie tylko o istnieniu interfejsu

2022-03-13 15:40 UTC, radamuspl commented on src/main/java/pl/com/bottega/ecommerce/sales/domain/service/TaxCalculatorFactory.java
> +public class TaxCalculatorFactory {
ta klasa jest zbędna - żadnej zmienności dzięki niej nie uzyskamy...

2022-03-13 20:23 UTC, AdrianPietrz commented
Wprowadzono poprawki

2022-03-16 19:46 UTC, radamuspl approved these changes

2022-03-16 19:46 UTC, merged