Lab 1_2
mto-2022-pn/lab1_2 pull request #5
Opened 2022-03-11 15:48 UTC by WojFar

Wojciech Farej
228730

2022-03-13 15:50 UTC, radamuspl requested changes

2022-03-13 15:50 UTC, radamuspl commented on src/main/java/pl/com/bottega/ecommerce/sales/domain/factory/Factory.java
> +public class Factory {
Nazwa tej klasy jest zbyt ogólna

2022-03-13 15:50 UTC, radamuspl commented on src/main/java/pl/com/bottega/ecommerce/sales/domain/invoicing/BookKeeper.java
> +    public Tax calulateTax(ProductType type, Money net) {
Chodziło o to, żeby można było logikę obliczania podatków dostarczać z zewnątrz. Tutaj jest po prostu osobna metoda w tej samej klasie (`BookKeeper`) - tak BTW resztą po co publiczna?
Prawidłowe rozwiązanie to rozbudowanie sygnatury metody `issuance` - `issuance(InvoiceRequest invoiceRequest, TaxCalculator calculator)`, gdzie `TaxCalculator` jest intefejsem, którego możemy mieć, potencjalnie, różne implementacje.

2022-03-13 15:50 UTC, radamuspl commented on src/main/java/pl/com/bottega/ecommerce/sales/domain/invoicing/TaxType.java
> +public enum TaxType {
To nam nic nie daje

2022-03-13 18:06 UTC, WojFar commented
Poprawiłem błędy zaczynając od 0-ra.
Wiem, że Force Push generalnie jest złą praktyką, ale że pracuję na gałęzi (w tym przypadku repozytorium) sam, a zmiany wymagały wręcz powrotu do stanu pierwotnego, to go użyłem (i żeby nie było konieczności tworzenia nowego pull requesta bez obejść)

2022-03-21 16:51 UTC, radamuspl approved these changes

2022-03-21 16:52 UTC, merged